name: bookstore_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: MonaSans
      fonts:
        - asset: fonts/Mona-Sans.ttf
        - asset: fonts/Mona-Sans-SemiBold.ttf
        - asset: fonts/Mona-Sans-Regular.ttf
        - asset: fonts/Mona-Sans-Medium.ttf
        - asset: fonts/Mona-Sans-Bold.ttf
        - asset: fonts/Mona-Sans-Black.ttf
        - asset: fonts/Mona-Sans-Light.ttf
        - asset: fonts/Mona-Sans-LightWide.ttf
  uses-material-design: true

  assets:
    - .env
